server:
  port: 8090

spring:
  datasource:

    driver_class_name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop
    #  url: jdbc:mysql://192.168.0.66:3306/ocserver?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    connection_timeout: 30000
    idleTimeout: 600000
  read_only: false
  max-lifetime: 1800000
  #  maximum_pool_size: 10
  maximum_pool_size: 50
  leak_detection_threshold: 300000


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean